# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pyqtgraph.Qt import QtCore, QtGui, QtWidgets
# from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget
import sys
import pyqtgraph


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 500)
        # MainWindow.move(-1200, 100)  # 将窗口左上角移动到屏幕上的 (100, 100) 位置
        pyqtgraph.setConfigOption('background', '#e0e0e0')
        pyqtgraph.setConfigOption('foreground', '#ffffff') 
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.graphicsView_2 = GraphicsLayoutWidget(self.groupBox)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout_2.addWidget(self.graphicsView_2)
        self.plot_writexzTime_decorate(self.graphicsView_2, [0, 2048], [-500, 500])
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.graphicsView_3 = GraphicsLayoutWidget(self.groupBox_2)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalLayout.addWidget(self.graphicsView_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.graphicsView_4 = GraphicsLayoutWidget(self.groupBox_2)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.horizontalLayout_3.addWidget(self.graphicsView_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.graphicsView_5 = GraphicsLayoutWidget(self.groupBox_2)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.horizontalLayout_4.addWidget(self.graphicsView_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = GraphicsLayoutWidget(self.groupBox_3)
        self.graphicsView.setObjectName("graphicsView")
        self.plot_writeTraj_decorate(self.graphicsView, [-300, 300], [0, 500])
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.printLog = QtWidgets.QTextEdit(self.groupBox_4)
        self.printLog.setReadOnly(True)
        self.printLog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.printLog.setAlignment(QtCore.Qt.AlignCenter)
        self.printLog.setObjectName("printLog")
        self.verticalLayout.addWidget(self.printLog)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.verticalLayout_8.setStretch(0, 3)
        self.verticalLayout_8.setStretch(1, 2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1480, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "LeapMotion"))
        self.checkBox.setText(_translate("MainWindow", "x"))
        self.checkBox_2.setText(_translate("MainWindow", "z"))
        self.checkBox_3.setText(_translate("MainWindow", "x_speed"))
        self.checkBox_4.setText(_translate("MainWindow", "z_speed"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Radar"))
        self.label_2.setText(_translate("MainWindow", "udoppler-t"))
        self.label_3.setText(_translate("MainWindow", "  Range-t "))
        self.label_4.setText(_translate("MainWindow", "  Angle-t "))
        self.groupBox_3.setTitle(_translate("MainWindow", "result"))
        self.groupBox_4.setTitle(_translate("MainWindow", "log"))
        self.printLog.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action.setText(_translate("MainWindow", "开始"))

    def plot_writeTraj_decorate(self, graphicsView, xRange_, yRange_):
            
            plot_writeTraj = graphicsView.addPlot(title='绘制点云')
            plot_writeTraj.hideButtons()  #禁用'A'按键
            # self.plot_pd.setMenuEnabled(False) #禁用右键菜单
            plot_writeTraj.setMouseEnabled(x=False, y=False)  # 禁用轴操作
        
            # 添加网格
            # self.plot_pd.showGrid(x=True, y=True)  # 把X和Y的表格打开
            plot_writeTraj.setRange(xRange=xRange_, yRange=yRange_, padding=0)
            # self.plot_pd.setLabel(axis='left', text='y')  # 靠左
            # self.plot_pd.setLabel(axis='bottom', text='x')
            # 关闭坐标轴
            plot_writeTraj.hideAxis('bottom')
            plot_writeTraj.hideAxis('left')
            plot_writeTraj.setTitle('手写轨迹')  # 表格的名字
            plot_writeTraj.setContentsMargins(0, 0, 0, 0)
            plot_writeTraj.getAxis('bottom').setHeight(0)
            plot_writeTraj.getAxis('left').setWidth(0)

            graphicsView.ci.layout.setContentsMargins(0, 0, 0, 0)
            graphicsView.ci.layout.setSpacing(0)
            # # 添加背景图片
            # image = 'code/image/background.jpg'
            # rgb = cv2.imread(image, cv2.COLOR_BGR2RGB)
            # rgb = cv2.rotate(rgb, cv2.cv2.ROTATE_90_CLOCKWISE)
            # # add an image, scaled
            # img = pg.ImageItem(rgb[:, :, [2,1,0]])
            # # img.scale(0.01, 0.2)
            # img.setZValue(-100)
            # rect = QtCore.QRectF(-20,0,40,100)#背景照片铺满坐标
            # img.setRect(rect)
            # self.plot_pd.addItem(img)
            # pen=None, symbol='o',symbolBrush='r',symbolPen = None, symbolSize=15
            self.plot_writeTraj_leap = plot_writeTraj.plot(pen=pyqtgraph.mkPen(color=(0, 0, 0),width=12), connect='finite')

    def plot_writexzTime_decorate(self, graphicsView, xRange_, yRange_):
            
            plot_writeTraj = graphicsView.addPlot(title='绘制轨迹')
            plot_writeTraj.hideButtons()  #禁用'A'按键
            plot_writeTraj.setMouseEnabled(x=False, y=False)  # 禁用轴操作
            plot_writeTraj.setRange( yRange=yRange_, padding=0)

            plot_writeTraj.hideAxis('bottom')
            plot_writeTraj.hideAxis('left')
            plot_writeTraj.setContentsMargins(0, 0, 0, 0)
            plot_writeTraj.getAxis('bottom').setHeight(0)
            plot_writeTraj.getAxis('left').setWidth(0)

            graphicsView.ci.layout.setContentsMargins(0, 0, 0, 0)
            graphicsView.ci.layout.setSpacing(0)

            self.plot_writexTime_leap = plot_writeTraj.plot(pen=pyqtgraph.mkPen(color=(255, 120, 0),width=4), connect='finite')
            self.plot_writezTime_leap = plot_writeTraj.plot(pen=pyqtgraph.mkPen(color=(120, 0, 255),width=4), connect='finite')

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.show()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # subWin = Qt_pet()
    sys.exit(app.exec_())